- name: clone sngsk.info repository
  git:
    repo: https://github.com/nosada/sngsk.info.git
    dest: /opt/sngsk.info

- name: copy nginx configs for mastodon to /etc/nginx/conf.d/
  copy:
    remote_src: yes
    src: "/opt/sngsk.info/nginx/host/conf.d/{{ item }}"
    dest: "/etc/nginx/conf.d/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - mastodon.conf
  notify: activate nginx.service
