- name: install mackerel-agent config for mstdnspawn
  become: yes
  template:
          src: for_application.conf.j2
          dest: "/etc/mackerel-agent/conf.d/{{ item }}.conf"
          mode: 0644
          owner: root
          group: root
  with_items:
          - "{{ domains }}"
  notify: activate mackerel-agent
