- name: install mackerel-agent config
  become: yes
  template:
          src: mackerel-agent.conf.j2
          dest: /etc/mackerel-agent/mackere-agent.conf
          mode: 0644
          owner: root
          group: root
  notify: activate mackerel-agent
  when: mackerel_api_key is defined
