- name: upgrade packages and package databases
  pacman:
          state: latest
          upgrade: yes
          update_cache: yes

- name: install daily-used packages
  pacman:
          state: latest
          name:
                  - arch-install-scripts
                  - btrfs-progs
                  - cowsay
                  - colordiff
                  - dfc
                  - fortune-mod
                  - fish
                  - fzf
                  - go
                  - git
                  - htop
                  - neovim
                  - polkit
                  - perl
                  - perl-data-dump
                  - reflector
                  - rsync
                  - unbound
                  - tmux
                  - tree

- name: install base-devel package group
  pacman:
          state: latest
          name:
                  - base-devel
