- name: upgrade packages and package databases
  pacman:
    state: latest
    upgrade: yes
    update_cache: yes

- name: install daily-used packages
  pacman:
    state: latest
    name:
      - arch-install-scripts
      - aria2
      - btrfs-progs
      - ccache
      - cowsay
      - colordiff
      - dfc
      - dnscrypt-proxy
      - docker
      - docker-compose
      - fortune-mod
      - fish
      - fzf
      - geoip2-database
      - git
      - go
      - htop
      - jq
      - libmaxminddb
      - mmdblookup
      - neovim
      - optipng
      - pacman-contrib
      - pacmatic
      - polkit
      - perl
      - perl-data-dump
      - python-setuptools
      - reflector
      - rsync
      - unbound
      - upx
      - tmux
      - tree

- name: install base-devel package group
  pacman:
    state: latest
    name:
      - base-devel

- name: clean package cache for 'pacman -U'
  become: yes
  shell: "pacman --noconfirm -Scc"
