- name: upgrade packages and package databases
  pacman:
    state: latest
    upgrade: yes
    update_cache: yes

- name: install base-devel package group
  pacman:
    state: latest
    name:
      - base-devel

- name: install daily-used packages
  pacman:
    state: latest
    name:
      - arch-install-scripts
      - aria2
      - btrfs-progs
      - ccache
      - colordiff
      - cowsay
      - dfc
      - dnscrypt-proxy
      - docker
      - docker-compose
      - dosfstools
      - fish
      - fortune-mod
      - fzf
      - git
      - gzip
      - htop
      - inetutils
      - jq
      - less
      - lolcat
      - mkosi
      - neovim
      - nodejs
      - pacman-contrib
      - polkit
      - reflector
      - rsync
      - systemd-ukify
      - tmux
      - tree
      - unbound
      - yarn

- name: reinnstall systemd and libsystemd to specified version
  become: yes
  shell: "pacman --noconfirm -U {{ item }}"
  with_items:
    - "https://archive.archlinux.org/packages/s/systemd/systemd-{{ systemd_version }}-x86_64.pkg.tar.xz"
    - "https://archive.archlinux.org/packages/l/libsystemd/libsystemd-{{ systemd_version }}-x86_64.pkg.tar.xz"
  when: systemd_version is defined and systemd_version != ""

- name: generate initramfs for all of installed kernels
  become: yes
  shell: "mkinitcpio -P"

- name: clean package cache for 'pacman -U'
  become: yes
  shell: "pacman --noconfirm -Scc"
