- name: download dotfile repository to homedir
  git:
    force: yes
    repo: https://github.com/nosada/dotfiles.git
    dest: "/home/{{ ansible_user }}/.dotfiles"

- name: clean dotfiles
  shell: "/home/{{ ansible_user }}/.dotfiles/clean.sh"

- name: deploy dotfiles
  shell: "/home/{{ ansible_user }}/.dotfiles/deploy.sh"

- name: download personal scripts
  git:
    force: yes
    repo: https://github.com/nosada/scripts.git
    dest: "/tmp/scripts"

- name: install personal scripts
  become: yes
  shell: "cd /tmp/scripts; cp qutorbrowser/config.json.tmpl qutorbrowser/config.json; make install"

- name: install .gitconfig to ${HOME}
  copy:
    src: .gitconfig
    dest: "/home/{{ ansible_user }}/.gitconfig"
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
