- name: construct server as sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
    - install_packages
    - install_configs
    - install_sngsk.info_configs
    - activate_services

- name: configure mackerel-agent
  hosts: sngsk.info
  become: yes
  roles:
    - install_mackerel_conf_for_application
    - install_mackerel_conf_for_nspawn_container
    - install_mackerel_conf_for_docker_container

- name: set up docker container for sngsk.info with docker-compose
  hosts: sngsk.info
  roles:
    - enable_iptables_docker
    - use_docker_in_sngsk.info
    - disable_iptables_docker
