- name: construct server as host of nspawn container
  hosts: sngsk.info
  become: yes
  roles:
          - install_packages
          - install_configs

- name: build and run nspawn container on sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
          - prepare_nspawn_containers
  vars:
          containers:
                  - sngskspawn

- name: construct server as sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
          - install_sngsk.info_configs
          - activate_services

- name: configure mackerel-agent
  hosts: sngsk.info
  become: yes
  roles:
          - install_mackerel_conf_for_sngsk.info
  vars:
          container: sngskspawn
