- name: construct server as host of nspawn container
  hosts: sngsk.info
  become: yes
  roles:
          - install_packages
          - install_configs

- name: build and run nspawn container on sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
          - prepare_nspawn_containers

- name: construct server as sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
          - install_sngsk.info_configs
          - activate_services

- name: set up mastodon on sngsk.info
  hosts: sngsk.info
  become: yes
  roles:
          - set_up_mastodon_on_sngsk.info

- name: make life easier
  hosts: sngsk.info
  roles:
          - make_life_easier
