- name: construct server as sngsk.info
  hosts: common
  become: yes
  roles:
    - install_packages
    - install_configs
    - install_sngsk.info_configs
    - activate_services

- name: configure mackerel-agent
  hosts: common
  become: yes
  roles:
    - install_mackerel_conf_for_application
    - install_mackerel_conf_for_nspawn_container
