- name: install pacman.conf
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
    mode: 0644
    owner: root
    group: root

- name: create /etc/pacman.d/hooks
  file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: 0755
    owner: root
    group: root

- name: create /var/tmp/makepkg
  file:
    path: /var/tmp/makepkg
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: install mirrorupgrade.hook to /etc/pacman.d/hooks
  copy:
    src: mirrorupgrade.hook
    dest: /etc/pacman.d/hooks/mirrorupgrade.hook
    mode: 0644
    owner: root
    group: root

- name: install makepkg.conf
  template:
    src: makepkg.conf.j2
    dest: /etc/makepkg.conf
    mode: 0644
    owner: root
    group: root

- name: install nsswitch.conf to /etc/nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    mode: 0644
    owner: root
    group: root

- name: install dnscrypt-proxy.toml to /etc/dnscrypt-proxy/
  copy:
    src: dnscrypt-proxy.toml
    dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    mode: 0644
    owner: root
    group: root
  notify:
    - restart dnscrypt-proxy.service
    - disable and stop dnscrypt-proxy.socket

- name: install unbound.conf to /etc/unbound/
  copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart unbound.service

- name: install resolved.conf to /etc/systemd/
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart systemd-networkd.service
    - restart systemd-resolved.service

- name: check /etc/resolv.conf
  stat:
    path: /etc/resolv.conf
  register:
    resolv_conf_status

- name: remove /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent
  when:
    resolv_conf_status.stat.exists and (resolv_conf_status.stat.islink is defined and resolv_conf_status.stat.islink)

- name: install /etc/resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart systemd-networkd.service
    - restart systemd-resolved.service

- name: set locale as en_US.UTF-8
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: install shm.conf to /etc/tmpfiles.d/
  copy:
    src: shm.conf
    dest: /etc/tmpfiles.d/shm.conf
    mode: 0644
    owner: root
    group: root

- name: install ramdisk.conf to /etc/tmpfiles.d/
  template:
    src: ramdisk.conf.j2
    dest: /etc/tmpfiles.d/ramdisk.conf
    mode: 0644
    owner: root
    group: root
