- name: install pacman.conf
  copy:
          src: pacman.conf
          dest: /etc/pacman.conf
          mode: 0644
          owner: root
          group: root

- name: create /etc/pacman.d/hooks
  file:
          path: /etc/pacman.d/hooks
          state: directory
          mode: 0755
          owner: root
          group: root

- name: install mirrorupgrade.hook to /etc/pacman.d/hooks
  copy:
          src: mirrorupgrade.hook
          dest: /etc/pacman.d/hooks/mirrorupgrade.hook
          mode: 0644
          owner: root
          group: root

- name: install makepkg.conf
  copy:
          src: makepkg.conf
          dest: /etc/makepkg.conf
          mode: 0644
          owner: root
          group: root

- name: install nsswitch.conf to /etc/nsswitch.conf
  copy:
          src: nsswitch.conf
          dest: /etc/nsswitch.conf
          mode: 0644
          owner: root
          group: root

- name: install resolved.conf to /etc/systemd/
  copy:
          src: resolved.conf
          dest: /etc/systemd/resolved.conf
          mode: 0644
          owner: root
          group: root
  notify:
          - restart unbound.service
          - restart systemd-networkd.service
          - restart systemd-resolved.service

- name: set locale as en_US.UTF-8
  locale_gen:
          name: en_US.UTF-8
          state: present

- name: install shm.conf to /etc/tmpfiles.d/
  copy:
          src: shm.conf
          dest: /etc/tmpfiles.d/shm.conf
          mode: 0644
          owner: root
          group: root
