- name: activate update-container.service
  systemd:
          daemon-reload: yes
          enabled: yes
          name: update-container.service
          state: restarted

- name: activate update-container.timer
  systemd:
          daemon-reload: yes
          enabled: yes
          name: update-container.timer
          state: restarted

- name: activate wake-up-nginx.service
  systemd:
          daemon-reload: yes
          enabled: yes
          name: wake-up-nginx.service
          state: restarted

- name: activate wake-up-nginx.timer
  systemd:
          daemon-reload: yes
          enabled: yes
          name: wake-up-nginx.timer
          state: restarted
