- name: install check_docker_container to /usr/local/bin/
  copy: yes
  file:
    src: check_docker_container
    dest: /usr/local/bin/check_docker_container
    mode: 0755
    owner: root
    group: root

- name: create directory /etc/mackerel-agent/conf.d/
  become: yes
  file:
    path: /etc/mackerel-agent/conf.d
    state: directory
    owner : root
    group: root

- name: install mackerel-agent config for docker containers
  become: yes
  template:
    src: for_container.conf.j2
    dest: "/etc/mackerel-agent/conf.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "{{ docker_containers }}"
  notify: activate mackerel-agent

- name: install docker_metric.conf to /etc/mackerel-agent/conf.d
  become: yes
  copy:
    src: docker_metric.conf
    dest: /etc/mackerel-agent/conf.d/docker_metric.conf
    mode: 0644
    owner: root
    group: root
  notify: activate mackerel-agent
