- name: install daily-used packages
  become: yes
  pacman:
          upgrade: yes
          update_cache: yes
          state: latest
          name:
                  - fish
                  - neovim
                  - tmux

- name: install neovim-symlinks
  aur:
          skip_pgp: yes
          user: "{{ ansible_user }}"
          name: neovim-symlinks

- name: install daily-used AUR packages
  aur:
          skip_pgp: yes
          user: "{{ ansible_user }}"
          name: "{{ item }}"
  with_items:
          - cower
          - fzf
          - pacaur
          - alsi

- name: download dotfile repository to homedir
  git:
          repo: https://github.com/nosada/dotfiles.git
          dest: "/home/{{ ansible_user }}/.dotfiles"

- name: set up dotfiles
  shell: "/home/{{ ansible_user }}/.dotfiles/deploy.sh"
