- name: install daily-used packages
  become: yes
  pacman:
          upgrade: yes
          update_cache: yes
          state: latest
          name:
                  - fish
                  - fzf
                  - neovim
                  - tmux
                  - colordiff

- name: create pacaur/ to ${HOME}/.cache/
  file:
          name: "/home/{{ ansible_user }}/.cache/pacaur/"
          state: directory
          mode: 0755
          owner: "{{ ansible_user }}"
          group: "{{ ansible_user }}"

- name: install neovim-symlinks
  become: yes
  aur:
          skip_pgp: yes
          user: "{{ ansible_user }}"
          name: neovim-symlinks

- name: install daily-used AUR packages
  become: yes
  aur:
          skip_pgp: yes
          user: "{{ ansible_user }}"
          dir: "/home/{{ ansible_user }}/.cache/pacaur/"
          name: "{{ item }}"
  with_items:
          - cower
          - pacaur
          - alsi
          - python-lolcat

- name: remove aur/ on ${HOME}/
  file:
          name: "/home/{{ ansible_user }}/aur"
          state: absent

- name: download dotfile repository to homedir
  git:
          repo: https://github.com/nosada/dotfiles.git
          dest: "/home/{{ ansible_user }}/.dotfiles"

- name: clean dotfiles
  shell: "/home/{{ ansible_user }}/.dotfiles/clean.sh"

- name: deploy dotfiles
  shell: "/home/{{ ansible_user }}/.dotfiles/deploy.sh"
