- name: set up home directory
  hosts: common
  roles:
    -  symlink_cache_directory

- name: install packages and configs
  become: yes
  hosts: common
  roles:
    - install_connection_configs
    - install_arch_packages
    - install_configs

- name: install AUR packages
  hosts: common
  roles:
    - install_aur_packages

- name: set up fish shell
  hosts: common
  roles:
    - set_up_user_environment
    - set_up_fish_shell

- name: activate mackerel-agent
  hosts: common
  roles:
    - activate_mackerel_agent
