- name: install iptables rules
  copy:
          src: iptables.rules
          dest: /etc/iptables/iptables.rules
          mode: 0644
          owner: root
          group: root
  notify: restart iptables.service

- name: install ip6tables rules
  copy:
          src: ip6tables.rules
          dest: /etc/iptables/ip6tables.rules
          mode: 0644
          owner: root
          group: root
  notify: restart ip6tables.service

- name: install sshd_config
  copy:
          src: sshd_config
          dest: /etc/ssh/sshd_config
          mode: 0644
          owner: root
          group: root
  notify: restart sshd.service

- name: install pacman.conf
  copy:
          src: pacman.conf
          dest: /etc/pacman.conf
          mode: 0644
          owner: root
          group: root

- name: create /etc/pacman.d/hooks
  file:
          path: /etc/pacman.d/hooks
          state: directory
          mode: 0755
          owner: root
          group: root

- name: install mirrorupgrade.hook to /etc/pacman.d/hooks
  copy:
          src: mirrorupgrade.hook
          dest: /etc/pacman.d/hooks/mirrorupgrade.hook
          mode: 0644
          owner: root
          group: root

- name: install nsswitch.conf to /etc/nsswitch.conf
  copy:
          src: nsswitch.conf
          dest: /etc/nsswitch.conf
          mode: 0644
          owner: root
          group: root
