- name: create directory /etc/mackerel-agent/conf.d/
  become: yes
  file:
    path: /etc/mackerel-agent/conf.d
    state: directory
    owner : root
    group: root

- name: install mackerel-agent config for nspawn containers
  become: yes
  template:
    src: for_container.conf.j2
    dest: "/etc/mackerel-agent/conf.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "{{ containers }}"
  notify: activate mackerel-agent
