- name: upgrade packages and package databases
  become: yes
  pacman:
          state: latest
          upgrade: yes
          update_cache: yes

- name: install required packages for sngsk.info
  pacman:
          state: latest
          name:
                  - certbot
                  - certbot-nginx
                  - git
                  - nginx
                  - reflector
                  - unbound
