- name: install required packages for sngsk.info
  pacman:
          state: latest
          name:
                  - certbot
                  - certbot-nginx
                  - git
                  - nginx
                  - reflector
                  - unbound
