- name: install required packages for sngsk.info
  pacman:
          upgrade: yes
          update_cache: yes
          state: latest
          name:
                  - certbot
                  - certbot-nginx
                  - nginx
                  - reflector
                  - unbound
