- name: restart dnscrypt-proxy.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: dnscrypt-proxy.service
    state: restarted

- name: disable and stop dnscrypt-proxy.socket
  systemd:
    daemon_reload: yes
    enabled: no
    name: dnscrypt-proxy.socket
    state: stopped

- name: restart unbound.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: unbound.service
    state: restarted

- name: restart systemd-networkd.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: systemd-networkd.service
    state: restarted

- name: restart systemd-resolved.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: systemd-resolved.service
    state: restarted

- name: restart systemd-logind.service
  systemd:
    daemon_reload: yes
    name: systemd-logind.service
    state: restarted

- name: restart systemd-swap.service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: systemd-swap.service
    state: restarted
