#!/bin/bash

nspawn-execute() {
	pid=$(machinectl -a -l status $1 | grep Leader | awk '{print $2}');
	echo "Execute on $1: nsenter -U -m -i -n -p ${@:2}";
	nsenter -U -m -i -n -p ${@:2}
}

nspawn-execute-all() {
	for i in $(machinectl list | grep nspawn | awk '{print $1}');
	do
		nspawn-execute $i "${@:1}";
	done
}

nspawn-execute-all pacman -Syu --noconfirm
nspawn-execute-all pacman -Scc --noconfirm
