#!/bin/bash

start-nspawn-container() {
	while read -r container
	do
		machinectl show "$container" 1> /dev/null 2> /dev/null
		result=$?
		if [ $result -eq 0  ]; then
			echo "$container already running"
		else
			echo "$container not running yet, starting..."
			machinectl start "$container"
		fi
	done < <(find /var/lib/machines -mindepth 1 ! -name '*.lck' -exec basename -a {} + | sed -e 's/.raw//g')
}

start-nspawn-container
