- name: uninstall vi & vim for preparation of installing neovim-symlinks
  become: yes
  pacman:
          state: absent
          name:
                - vi
                - vim
                - vim-runtime

- name: create symlink to /usr/bin/ for pod2man
  become: yes
  file:
          src: /usr/bin/core_perl/pod2man
          dest: /usr/bin//pod2man
          owner: root
          group: root
          state: link

- name: install neovim-symlinks
  include_tasks: library/aur/pkg.yml pkg_name=neovim-symlinks

- name: install alsi
  include_tasks: library/aur/pkg.yml pkg_name=alsi

- name: install cdu
  include_tasks: library/aur/pkg.yml pkg_name=cdu

- name: install mkosi
  include_tasks: library/aur/pkg.yml pkg_name=mkosi

- name: install python-lolcat
  include_tasks: library/aur/pkg.yml pkg_name=python-lolcat

- name: install ghq
  include_tasks: library/aur/pkg.yml pkg_name=ghq

- name: install urlview
  include_tasks: library/aur/pkg.yml pkg_name=urlview

- name: install mackerel-agent
  include_tasks: library/aur/pkg.yml pkg_name=mackerel-agent
  when: mackerel_api_key is defined

- name: install mackerel-agent-plugins-git
  include_tasks: library/aur/pkg.yml pkg_name=mackerel-agent-plugins-git
  when: mackerel_api_key is defined

- name: install mackerel-check-plugins-git
  include_tasks: library/aur/pkg.yml pkg_name=mackerel-check-plugins-git
  when: mackerel_api_key is defined

- name: install mkr
  include_tasks: library/aur/pkg.yml pkg_name=mkr
  when: mackerel_api_key is defined
