- name: check whether neovim-symlinks already installed
  shell: "pacman -Qs neovim-symlinks"
  register: neovim_symlinks_installed
  failed_when: false

- name: uninstall vi & vim if neovim-symlinks NOT installed yet
  become: yes
  pacman:
    state: absent
    name:
      - vi
      - vim
      - vim-runtime
  when:
    neovim_symlinks_installed.rc != 0

- name: create symlink to /usr/bin/ for pod2man
  become: yes
  file:
    src: /usr/bin/core_perl/pod2man
    dest: /usr/bin/pod2man
    owner: root
    group: root
    state: link

- name: install packages hosted in AUR
  include_tasks:
    file: library/aur/pkg.yml
    apply:
      vars:
        pkg_name: neovim-symlinks
        pkg_name: neofetch-git
        pkg_name: cdu
        pkg_name: mkosi
        pkg_name: python-lolcat
        pkg_name: ghq
        pkg_name: urlview

- name: install packages whom tmux-mem-cpu-load-git depends
  become: yes
  pacman:
    state: latest
    name:
      - jsoncpp
      - rhash
      - shared-mime-info
      - cmake

- name: install tmux-mem-cpu-load-git
  include_tasks:
    file: library/aur/pkg.yml
    apply:
      vars:
        pkg_name: tmux-mem-cpu-load-git

- name: install Mackerel relate packages
  include_tasks:
    file: library/aur/pkg.yml
    apply:
      vars:
        pkg_name: mackerel-agent
        pkg_name: mackerel-agent-plugins-git
        pkg_name: mackerel-check-plugins-git
        pkg_name: mkr
  when: mackerel_api_key is defined
